### ISSUE TITLE
TKTapRecognizer "numberOfTapsRequired" doesn't work

### ISSUE THREAD

**Issue by nsandhu** [prime31/TouchKit#2]
The class TKTap Recognizer doesn't actually do anything with the public int "numberOfTapsRequired", so when you try to adjust it to do a double tap or anything it just doesnt work. I looked for any references to it's usage in monodevelop and it found none.

public class TKTapRecognizer : TKAbstractGestureRecognizer
{
        public int numberOfTapsRequired = 1;
	public int numberOfTouchesRequired = 1;

...
}

**Comment by TimBasteiLuebbe** [comment]
Same problem here. Did anyone find a workaround?

If not I will try to fix it later. It's not on the top of my to do list for now.

**Comment by mrhotgen1968** [comment]
In...

TKTapRecognizer in the function...

touchesEnded()

Instead of just...

				state = TKGestureRecognizerState.Recognized;

You will need something like...

			if(touches[0].tapCount >= numberOfTapsRequired)
			{
				state = TKGestureRecognizerState.Recognized;
			}

Assuming it is the first touch that you are tracking.
