### ISSUE TITLE
TKPinchRecognizer accidentally counts the first touch twice

### ISSUE THREAD

**Issue by rednebmas** [prime31/TouchKit#30]
I am not completely familiar with your codebase yet, but I have found a temporary solution to the problem, and the solution may help you pinpoint the problem.

It is occurring on a Windows 7 and a Windows 8 touchscreen device.

In the method `touchesBegan`, the line `if( touches[i].phase == TouchPhase.Began )` is causing the problem. Touch 0 and touch 1 are identical (they have the same fingerID). 

My temporary solution uses the following code inside the problematic if statement:
```Csharp
if (this.isUniqueID(_trackingTouches, touches[i])) {
	_trackingTouches.Add( touches[i] );
	// DebugConsole.Log(string.Format("Touch :: Pos: {1}, ID: {2}", i, touches[i].position, touches[i].fingerId));
}

// .... after the touchesBegan method
private bool isUniqueID(List<TKTouch> touches, TKTouch touch)
{
	for (int i = 0; i < touches.Count; i++) {
		if (touches[i].fingerId == touch.fingerId)
		{
			return false;
		}
	}
	return true;
}

```

Also, it is worth noting that because of this, the pinch gesture in the first demo scene does not work.

**Comment by prime31** [comment]
That is definitely not normal. fingerIds should always be unique. I only
have access to one touchscreen device running Win 10 at the moment but I'll
do some testing on there and report a bug to Unity if they are in face
duplicating touchIds.


Mike

**Comment by rednebmas** [comment]
I've determined that by commenting out the following line https://github.com/prime31/TouchKit/blob/master/Assets/TouchKit/TouchKit.cs#L154, the demo works correctly. It seems that the touch is being counted twice. Once as a mouse click, and another time as a touch.
