### ISSUE TITLE
TKTouchPadRecognizer doesn't call its gestureCompleteEvent

### ISSUE THREAD

**Issue by tanis2000** [prime31/TouchKit#45]
I'm leaving a note there as I'm investigating this problem myself.

It looks like the `gestureCompleteEvent` of `TKTouchPadRecognizer` is never being called. 
I tried to debug the problem and it looks like the `isTrackingTouch` method returns false for the ending touch, which is kind of weird.

I'm registering the recognizer just like in the demo:

```
        	AnimationCurve touchPadInputCurve = AnimationCurve.Linear( 0.0f, 0.0f, 1.0f, 1.0f );
            var recognizer = new TKTouchPadRecognizer( new TKRect( 0f, 50f, Game.DesignWidth, Game.DesignHeight-50 ) );
			recognizer.inputCurve = touchPadInputCurve;

			recognizer.gestureRecognizedEvent += ( r ) =>
			{
				//Camera.main.transform.position -= new Vector3( recognizer.deltaTranslation.x, recognizer.deltaTranslation.y ) / 100;
				Debug.Log( "touchpad recognizer fired: " + r );
			};

			// continuous gestures have a complete event so that we know when they are done recognizing
			recognizer.gestureCompleteEvent += r =>
			{
				Debug.Log( "touchpad gesture complete" );
			};
			TouchKit.addGestureRecognizer( recognizer );
```

If you put a breakpoint in `isTrackingTouch` you can see that `_trackingTouches` is empty, but I cannot find who's clearing it before it should be cleared.

I might need a hand with this. Cheers!

**Comment by tanis2000** [comment]
This is driving me mad. I can't find anything that clears the `_trackingTouches` list by calling the `reset` function there... https://github.com/prime31/TouchKit/blob/master/Assets/TouchKit/Recognizers/TKAbstractGestureRecognizer.cs#L193

**Comment by prime31** [comment]
I'll try to scrape together some time to give this a look tonight.

**Comment by prime31** [comment]
Oddly enough everything seems to work fine for me...

**Comment by prime31** [comment]
Driver error! You cant remove and re-add a recognizer every frame. it will never complete!
