### ISSUE TITLE
Example scenes do not work with newer versions of Unity

### ISSUE THREAD

**Issue by bhison** [prime31/TouchKit#65]
As someone just getting my head in to this library, it doesn't help that everything is built using some custom UI scripts rather than the Unity UI system introduced in Unity 5. This has rendered the examples almost entirely non-functional.

**Comment by prime31** [comment]
The UI used in the demos is absolutely standard Unity immediate mode GUI. It is the absolute easiest way to have any example code as there is no disconnect between the code for the button and the code that runs when a button is pressed. Using a Canvas you end up with a pile of extra GaneObjects all connected by invisible magic to the code that runs when buttons are pressed.
