### ISSUE TITLE
[BUG] Horizontal swipe not recognized if there was an arbitraty dragging before

### ISSUE THREAD

**Issue by Deepscorn** [prime31/TouchKit#67]
Repro:
1. Create a scrollview
2. Init horizontal swipe (TKSwipeRecognizer)
3. Unset triggerWhenCriteriaMet (see details https://github.com/prime31/TouchKit/issues/66)
4. Hold the left mouse button and drag slowly from left to right, then from right to left (for example). Then make a fast drag and only now release the button.

Result:
recognizer do not fire gestureRecognizedEvent

Expected behaviour:
recognizer fires gestureRecognizedEvent. That's how it works in vkontakte app when watching photo album for example. 

Why is that important:
User may just dragged a bit before swiping because he is inside the bus which makes him shake from time to time

**Comment by prime31** [comment]
If you look at the code this is the expected behavior. The definition of a swipe is a touch with a move in a specific direction. The instant you change directions it is no longer a swipe and is just random dragging.

**Comment by Deepscorn** [comment]
Just to be sure you understand me:
I did a fast move in a specific direction (1) and successfully received swipe event.
But if I make random dragging and then (not releasing the mouse button) will do (1) - I do not receive swipe

**Comment by prime31** [comment]
Precisely correct. The instant you change direction it is no longer a swipe. Now you can certainly make a custom gesture recognizer that looks for any movement in a direction of a specific length regardless of previous input but it wouldn't be a swipe.
